#!/bin/bash
# setup-dbt.sh - Helper script to set up dbt with Snowglobe

set -e

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ❄️ + ☁️  Snowglobe + dbt Setup Script"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Functions
print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

# Check if Snowglobe is running
check_snowglobe() {
    print_info "Checking if Snowglobe is running..."
    
    if curl -k -s https://localhost:8443/health > /dev/null 2>&1; then
        print_success "Snowglobe is running"
        return 0
    elif curl -s http://localhost:8084/health > /dev/null 2>&1; then
        print_warning "Snowglobe is running on HTTP only"
        SNOWGLOBE_PROTOCOL="http"
        SNOWGLOBE_PORT="8084"
        return 0
    else
        print_error "Snowglobe is not running"
        echo ""
        print_info "Start Snowglobe with:"
        echo "  docker-compose up -d"
        echo "  OR"
        echo "  python -m snowglobe_server.server"
        return 1
    fi
}

# Install dbt-snowflake
install_dbt() {
    print_info "Checking dbt-snowflake installation..."
    
    if command -v dbt &> /dev/null; then
        DBT_VERSION=$(dbt --version | grep "Core:" | awk '{print $2}')
        print_success "dbt already installed (version: $DBT_VERSION)"
        return 0
    else
        print_warning "dbt-snowflake not found"
        read -p "Install dbt-snowflake? [y/N] " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            pip install dbt-snowflake
            print_success "dbt-snowflake installed"
            return 0
        else
            print_error "dbt-snowflake is required"
            return 1
        fi
    fi
}

# Create profiles.yml
create_profiles() {
    print_info "Setting up dbt profiles..."
    
    DBT_DIR="$HOME/.dbt"
    PROFILES_FILE="$DBT_DIR/profiles.yml"
    
    # Create .dbt directory if it doesn't exist
    mkdir -p "$DBT_DIR"
    
    # Check if profiles.yml exists
    if [ -f "$PROFILES_FILE" ]; then
        print_warning "profiles.yml already exists at $PROFILES_FILE"
        read -p "Backup and create new profiles.yml? [y/N] " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            BACKUP_FILE="$PROFILES_FILE.backup.$(date +%Y%m%d_%H%M%S)"
            cp "$PROFILES_FILE" "$BACKUP_FILE"
            print_success "Backed up to $BACKUP_FILE"
        else
            print_info "Skipping profiles.yml creation"
            return 0
        fi
    fi
    
    # Get configuration from Snowglobe API or use defaults
    PROTOCOL="${SNOWGLOBE_PROTOCOL:-https}"
    PORT="${SNOWGLOBE_PORT:-8443}"
    
    # Create profiles.yml
    cat > "$PROFILES_FILE" << EOF
# dbt profiles for Snowglobe
# Generated by setup-dbt.sh on $(date)

snowglobe:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: localhost
      user: dev
      password: dev
      role: ACCOUNTADMIN
      database: DBT_DB
      warehouse: COMPUTE_WH
      schema: PUBLIC
      threads: 4
      client_session_keep_alive: false
      query_tag: dbt-snowglobe
      
      # Snowglobe-specific settings
      host: localhost
      port: $PORT
      protocol: $PROTOCOL
      insecure_mode: true
    
    test:
      type: snowflake
      account: localhost
      user: test
      password: test
      role: ACCOUNTADMIN
      database: DBT_TEST
      warehouse: COMPUTE_WH
      schema: PUBLIC
      threads: 2
      client_session_keep_alive: false
      query_tag: dbt-snowglobe-test
      host: localhost
      port: $PORT
      protocol: $PROTOCOL
      insecure_mode: true
EOF
    
    print_success "Created profiles.yml at $PROFILES_FILE"
}

# Create new dbt project
create_project() {
    read -p "Enter project name (or press Enter to skip): " PROJECT_NAME
    
    if [ -z "$PROJECT_NAME" ]; then
        print_info "Skipping project creation"
        return 0
    fi
    
    if [ -d "$PROJECT_NAME" ]; then
        print_error "Directory $PROJECT_NAME already exists"
        return 1
    fi
    
    print_info "Creating dbt project: $PROJECT_NAME"
    
    # Create project directory
    mkdir -p "$PROJECT_NAME"
    cd "$PROJECT_NAME"
    
    # Create directory structure
    mkdir -p models/staging models/marts models/intermediate
    mkdir -p tests macros seeds snapshots analyses
    
    # Create dbt_project.yml
    cat > dbt_project.yml << EOF
name: $PROJECT_NAME
version: 1.0.0
config-version: 2

profile: snowglobe

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  $PROJECT_NAME:
    materialized: table
    staging:
      materialized: view
      schema: staging
    marts:
      materialized: table
      schema: marts

seeds:
  $PROJECT_NAME:
    quote_columns: false
EOF
    
    # Create .gitignore
    cat > .gitignore << EOF
target/
dbt_packages/
logs/
.env
*.pyc
__pycache__/
.DS_Store
EOF
    
    # Create README
    cat > README.md << EOF
# $PROJECT_NAME

dbt project for Snowglobe

## Setup

1. Ensure Snowglobe is running:
   \`\`\`bash
   docker-compose up -d
   \`\`\`

2. Test connection:
   \`\`\`bash
   dbt debug
   \`\`\`

3. Run models:
   \`\`\`bash
   dbt run
   \`\`\`

## Project Structure

- \`models/staging/\` - Staging models (views)
- \`models/marts/\` - Mart models (tables)
- \`tests/\` - Custom data tests
- \`macros/\` - Custom macros
- \`seeds/\` - CSV seed files

## Commands

\`\`\`bash
dbt run          # Run all models
dbt test         # Run all tests
dbt seed         # Load seed data
dbt docs generate && dbt docs serve  # Generate docs
\`\`\`
EOF
    
    # Create sample staging model
    cat > models/staging/stg_sample.sql << EOF
{{
  config(
    materialized='view',
    tags=['staging']
  )
}}

-- Sample staging model
select
    1 as id,
    'Sample Record' as name,
    current_timestamp() as created_at
EOF
    
    # Create sample mart model
    cat > models/marts/mart_sample.sql << EOF
{{
  config(
    materialized='table',
    tags=['marts']
  )
}}

-- Sample mart model
with staging as (
    select * from {{ ref('stg_sample') }}
)

select
    id,
    upper(name) as name_upper,
    created_at,
    date_trunc('day', created_at) as created_date
from staging
EOF
    
    # Create schema.yml
    cat > models/schema.yml << EOF
version: 2

models:
  - name: stg_sample
    description: "Sample staging model"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: name
        description: "Sample name"
      - name: created_at
        description: "Record creation timestamp"
  
  - name: mart_sample
    description: "Sample mart model"
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: name_upper
        description: "Uppercase name"
EOF
    
    # Create sample seed
    cat > seeds/sample_data.csv << EOF
id,name,value
1,Item A,100
2,Item B,200
3,Item C,300
EOF
    
    cd ..
    
    print_success "Created dbt project: $PROJECT_NAME"
    print_info "Next steps:"
    echo "  cd $PROJECT_NAME"
    echo "  dbt debug"
    echo "  dbt run"
}

# Test dbt connection
test_connection() {
    print_info "Testing dbt connection..."
    
    # Use Snowglobe API test endpoint
    RESPONSE=$(curl -k -s https://localhost:8443/api/dbt/test-connection 2>/dev/null || echo '{"success":false}')
    
    if echo "$RESPONSE" | grep -q '"success":true'; then
        print_success "dbt connection test passed"
        
        # Show test results
        echo ""
        echo "Test Results:"
        echo "$RESPONSE" | python3 -c "import sys, json; data=json.load(sys.stdin); [print(f\"  {'✓' if c['status']=='passed' else '✗'} {c['check']}: {c['message']}\") for c in data.get('checks', [])]"
        return 0
    else
        print_error "dbt connection test failed"
        return 1
    fi
}

# Main menu
show_menu() {
    echo ""
    echo "What would you like to do?"
    echo ""
    echo "  1) Complete setup (recommended for first time)"
    echo "  2) Install dbt-snowflake only"
    echo "  3) Create profiles.yml only"
    echo "  4) Create new dbt project"
    echo "  5) Test dbt connection"
    echo "  6) View setup instructions"
    echo "  7) Exit"
    echo ""
    read -p "Enter choice [1-7]: " choice
    
    case $choice in
        1)
            complete_setup
            ;;
        2)
            install_dbt
            ;;
        3)
            create_profiles
            ;;
        4)
            create_project
            ;;
        5)
            test_connection
            ;;
        6)
            show_instructions
            ;;
        7)
            echo "Goodbye!"
            exit 0
            ;;
        *)
            print_error "Invalid choice"
            show_menu
            ;;
    esac
}

# Complete setup
complete_setup() {
    echo ""
    print_info "Starting complete setup..."
    echo ""
    
    # Check Snowglobe
    if ! check_snowglobe; then
        exit 1
    fi
    
    echo ""
    
    # Install dbt
    if ! install_dbt; then
        exit 1
    fi
    
    echo ""
    
    # Create profiles
    create_profiles
    
    echo ""
    
    # Create project
    create_project
    
    echo ""
    
    # Test connection
    test_connection
    
    echo ""
    print_success "Setup complete!"
    echo ""
    print_info "Next steps:"
    echo "  1. cd into your project directory"
    echo "  2. Run: dbt debug"
    echo "  3. Run: dbt run"
    echo "  4. Visit: https://localhost:8443/dashboard"
    echo ""
}

# Show instructions
show_instructions() {
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo "  dbt + Snowglobe Setup Instructions"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "1. Ensure Snowglobe is running:"
    echo "   docker-compose up -d"
    echo ""
    echo "2. Install dbt-snowflake:"
    echo "   pip install dbt-snowflake"
    echo ""
    echo "3. Create ~/.dbt/profiles.yml with this content:"
    echo ""
    echo "   snowglobe:"
    echo "     target: dev"
    echo "     outputs:"
    echo "       dev:"
    echo "         type: snowflake"
    echo "         account: localhost"
    echo "         user: dev"
    echo "         password: dev"
    echo "         host: localhost"
    echo "         port: 8443"
    echo "         protocol: https"
    echo "         insecure_mode: true"
    echo "         database: DBT_DB"
    echo "         warehouse: COMPUTE_WH"
    echo "         schema: PUBLIC"
    echo ""
    echo "4. Test connection:"
    echo "   dbt debug"
    echo ""
    echo "5. Run dbt commands:"
    echo "   dbt run"
    echo "   dbt test"
    echo "   dbt docs generate"
    echo "   dbt docs serve"
    echo ""
    echo "For more details, see DBT_GUIDE.md"
    echo ""
}

# Main execution
main() {
    # Check if running with arguments
    if [ $# -eq 0 ]; then
        show_menu
    else
        case $1 in
            --full|--complete)
                complete_setup
                ;;
            --install-dbt)
                install_dbt
                ;;
            --create-profiles)
                create_profiles
                ;;
            --create-project)
                shift
                PROJECT_NAME="$1"
                create_project
                ;;
            --test)
                test_connection
                ;;
            --help|-h)
                echo "Usage: $0 [OPTIONS]"
                echo ""
                echo "Options:"
                echo "  --full              Complete setup (profiles + project)"
                echo "  --install-dbt       Install dbt-snowflake"
                echo "  --create-profiles   Create profiles.yml"
                echo "  --create-project    Create new dbt project"
                echo "  --test              Test dbt connection"
                echo "  --help              Show this help message"
                echo ""
                echo "Run without arguments for interactive menu."
                ;;
            *)
                print_error "Unknown option: $1"
                echo "Run with --help for usage information"
                exit 1
                ;;
        esac
    fi
}

# Run main
main "$@"
